upload resume to s3
hoangr1010/Cupid pull request #134
Opened 2024-05-22 12:39 UTC by lnguyen2693

### Overall:
Users now can upload resume, update resume. Their resumes will be saved in aws s3

### File Changes:
- client/src/api/user.js : send resume file from frontend to backend
- client/src/pages/ProfilePage/index.jsx : form to upload a pdf file
- server/src/controllers/User.js : save resume link to database
- server/src/middleware/resumeUpload.js : function to upload resume to s3
- server/src/routes/User.js : 
- server/.env : add AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_BUCKET_LINK (check design doc)

### Test:
https://github.com/hoangr1010/Cupid/assets/137933787/af2c1127-3743-4ce3-aea3-2ec8d525f2a7

2024-05-22 13:43 UTC, hoangr1010 requested changes
<3 some review w luv

2024-05-22 13:43 UTC, hoangr1010 commented on client/src/api/user.js
> +  console.log(response);
sao ko dufng try catch, lỡ như nó bị error thì seo

2024-05-22 13:43 UTC, hoangr1010 commented on client/src/api/user.js
> +  await dispatch(updateUser(response.data.data));
với cả dùng toast nữa

2024-05-22 13:43 UTC, hoangr1010 commented on server/src/middleware/resumeUpload.js
> +  console.log("load resume to s3");
xoá bớt mấy cái console log for development

2024-05-22 14:08 UTC, hoangr1010 commented
Hi, t nghĩ m nên save cái path của cái file thôi, chớ đừng có save luôn cả url của bucket bởi vì là mốt mình thay đổi deployment thì url thay đổi ý. nên save cái path trong database, rồi lưu bucket url trên frontend, lấy path từ database ra + bucket url thì frontend access đc cái resource đấy

2024-05-23 10:43 UTC, hoangr1010 approved these changes
hi

2024-05-23 10:43 UTC, hoangr1010 commented on client/src/pages/ProfilePage/index.jsx
> +                src={`${process.env.REACT_APP_S3_BUCKET_LINK}/${user.resume_url}`}
<3

2024-05-23 12:16 UTC, khangnh107 approved these changes

2024-05-23 12:20 UTC, merged