Make UI for request dashboard + request creation form
hoangr1010/Cupid pull request #33
Opened 2024-04-12 04:02 UTC by khangnh107

### Overall:
- This code creates UI for request dashboard + request creation form.

### File Changes:
- client/src/pages/RequestDashboardPage
- client/src/pages/RequestCreatePage

### Test:
Server runs ok

<img width="1382" alt="Screenshot 2024-04-11 at 11 57 22 PM" src="https://github.com/hoangr1010/Cupid/assets/140891599/a630938d-c1ff-43d7-bec7-9b7e3795baa1">

<img width="1389" alt="Screenshot 2024-04-12 at 12 02 14 AM" src="https://github.com/hoangr1010/Cupid/assets/140891599/42cd19e4-7ea1-4bb2-a42f-a4e30654966a">

2024-04-13 01:15 UTC, hoangr1010 requested changes
Pls update associated Issues of this PR

2024-04-14 15:04 UTC, lnguyen2693 approved these changes

2024-04-14 15:09 UTC, linhkhanhhoang approved these changes

2024-04-15 15:43 UTC, hoangr1010 commented
@khangnh107 pls resolve conflict and merge this PR

2024-04-16 03:05 UTC, hoangr1010 approved these changes
LGTM!

2024-04-16 03:05 UTC, merged