Setup frontend
hoangr1010/Cupid pull request #6
Opened 2024-03-25 23:53 UTC by hoangr1010

Set up redux and tailwind (theme and common class)

2024-03-26 00:05 UTC, linhkhanhhoang approved these changes

2024-03-26 00:24 UTC, lnguyen2693 commented on clients/src/pages/LandingPage/index.jsx
> +        <div class="flex flex-col justify-center items-center bg-background min-h-screen w-screen">
Chrome gives me warnings that this should be className instead of class

2024-03-26 00:24 UTC, lnguyen2693 commented on clients/src/pages/LandingPage/index.jsx
> +const LangdingPage = () => {
spelling nè

2024-03-26 00:26 UTC, lnguyen2693 commented on clients/src/App.jsx
> +import LangdingPage from './pages/LandingPage';
spelling

2024-03-26 00:27 UTC, lnguyen2693 requested changes
see my comments :))

2024-03-27 02:25 UTC, lnguyen2693 approved these changes
LGTM!

2024-03-27 02:26 UTC, merged