Fix initial errors
hoangr1010/Cupid pull request #9
Opened 2024-03-29 03:06 UTC by khangnh107

Commit to fix initial errors such as not using ES6 export and singular noun in api route

2024-03-29 23:09 UTC, hoangr1010 requested changes

2024-03-29 23:09 UTC, hoangr1010 commented on server/index.js
> +app.use("/users", UserRouter);
chỗ này chắc ko cần 's' đâu nhỉ, về sau ko bị confused là có s hay ko

2024-03-30 12:35 UTC, lnguyen2693 commented on server/index.js
> +app.use("/users", UserRouter);
t đồng ý với hoàng á nên để /user thôi

2024-03-30 12:37 UTC, lnguyen2693 commented on server/index.js
> +app.use("/users", UserRouter);
t đồng ý với hoàng á nên để /user thôi

2024-03-31 01:28 UTC, khangnh107 commented on server/index.js
> +app.use("/users", UserRouter);
Done

2024-03-31 01:32 UTC, lnguyen2693 approved these changes
LGTM!

2024-04-01 02:32 UTC, hoangr1010 approved these changes

2024-04-01 02:32 UTC, merged