Matching algorithm (first-come-first-serve) based on scale
hoangr1010/Cupid pull request #97
Opened 2024-05-01 06:39 UTC by khangnh107

### Overall:
- Make a script that runs first-come-first-serve matching algorithm based on the "scale" field in Request Schema.

### File Changes:
- matching-algorithm/.gitignore
- matching-algorithm/models/Opening.js
- matching-algorithm/models/Request.js
- matching-algorithm/models/User.js
- matching-algorithm/package-lock.json
- matching-algorithm/package.json
- matching-algorithm/script/index.js
- matching-algorithm/utils/connectDB.js
- matching-algorithm/utils/date.js

### Test:

https://github.com/hoangr1010/Cupid/assets/140891599/d4dd1abe-b8af-490f-8a92-08b292e97a3f

2024-05-01 06:43 UTC, hoangr1010 reviewed
qua dinh, nhung mai review sau

2024-05-01 17:06 UTC, hoangr1010 requested changes
Great job my friend. Nhưng PR này đọc sẽ ko hiểu gì nếu ko có documentation. nên m có thể viết documentation (steps of algorithm) trên miro rồi cap quăng vào PR này. với cả add more comment ở mấy chỗ khó hiểu. THat's it 👯‍♀️

2024-05-01 17:06 UTC, hoangr1010 commented on matching-algorithm/script/index.js
> +  }
understandable nhưng add more comments, mới đọc lú nhẹ

2024-05-02 01:43 UTC, khangnh107 commented on matching-algorithm/script/index.js
> +  }
So that I know if the error happens when getting request or when getting openings

2024-05-02 01:43 UTC, khangnh107 commented on matching-algorithm/script/index.js
> +  requests.sort((a, b) => b.scale - a.scale);
Yea

2024-05-02 01:43 UTC, khangnh107 commented on matching-algorithm/script/index.js
> +  }
Ok

2024-05-02 01:43 UTC, khangnh107 commented on matching-algorithm/script/index.js
> +  }
T ghet m

2024-05-02 01:44 UTC, khangnh107 commented on matching-algorithm/script/index.js
> +  }
T cung co hieu LinkedIn Auth hoat dong nhu nao dau 😠

2024-05-02 01:47 UTC, khangnh107 commented on matching-algorithm/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Done

2024-05-03 17:54 UTC, merged